### ISSUE TITLE
Support fzf?

### ISSUE THREAD

**Issue by FranklinYu** [TD-Sky/conceal#1]
It would be nice if the application can fall back to `fzf` when `sk` is missing. I noticed that Skim is used only in

https://github.com/TD-Sky/conceal/blob/9f7af42cd631eba472cd615a9a3c6ba9e1c4cb7d/src/handlers/restore.rs#L50-L51

This seems fully compatible with `fzf`.

**Comment by TD-Sky** [comment]
How about making which fuzzy finder is used as a **feature**?

**Comment by FranklinYu** [comment]
I assume you mean allowing users to specify one. How would that be implemented? Via a command-line flag, or maybe an environment variable?

**Comment by TD-Sky** [comment]
> I assume you mean allowing users to specify one. How would that be implemented? Via a command-line flag, or maybe an environment variable?

Conditional compiling flag.

**Comment by FranklinYu** [comment]
I see, you were referring to [Cargo features](https://doc.rust-lang.org/cargo/reference/features.html). I’m not sure whether this is a good choice in the long run, though; this means that distribution packagers, instead of the end users themselve, decide the fuzzy finder. For example, `conceal` could graduate from AUR, or one can package it for [Homebrew](https://brew.sh) and [MacPorts](https://www.macports.org). I personally prefer making the decision at run-time. How does that sound to you?

**Comment by TD-Sky** [comment]
I'm going to design it with run-time decision.

Do you have any other suggestions?

**Comment by TD-Sky** [comment]
I want to add `--finder` with args `skim` or `fzf` like [navi](https://github.com/denisidoro/navi) to `conceal restore`.

Users could also pass value to environment variable `CONCEAL_FINDER` to decide the fuzzy finder.

**Comment by TD-Sky** [comment]
I have implemented my idea.

**Comment by FranklinYu** [comment]
I compiled the latest version of the `main` branch and it works perfect. Thanks a lot!
