### ISSUE TITLE
an “all” flag for “restore” command

### ISSUE THREAD

**Issue by FranklinYu** [TD-Sky/conceal#4]
I noticed that the `list` command has a handy `--all` flag to list more than the one associated with `$PWD`. Would it make sense to support the same feature for `restore` command? In other words, I would love to

```sh
conceal restore --all
```

And it should print the same list provided by `list --all` to Skim (or whatever finder I specified).

**Comment by TD-Sky** [comment]
No. I wish the restored files can be observed under current directory (recursively).

The all deleted items view may be more suitable in GUI.

**Comment by FranklinYu** [comment]
Thanks. It helps to learn that this is intended. I don’t have strong opinion about this.
